name: greytrix_ui_kit
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '0.17.0'
  flutter_typeahead: '3.1.3'
  charts_flutter: '0.10.0'
  google_maps_flutter: '2.0.3'
  flutter_plugin_android_lifecycle: '2.0.1'
  flutter_svg: '0.22.0'
  flutter_signature_pad: '3.0.0'
  file_picker: '3.0.3'
  universal_html: '2.0.8'
  table_calendar: '3.0.0'
  easy_web_view: '1.5.0'
  get: '4.1.4'
  flex_color_scheme: '3.0.1'
  dialog_flowtter: '0.3.1'
  # palette_generator: ^0.3.0
  # avatar_glow: ^2.0.1
  
  
dependency_overrides:
  permission_handler: '8.1.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/assets/images/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Light
      fonts:
        - asset: lib/assets/fonts/Montserrat-Light.ttf
        
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
